export const ROLES = {
  OWNER: 'OWNER',
  MANAGER: 'MANAGER',
  SUPERVISOR: 'SUPERVISOR',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  MACHINE_OPERATOR: 'MACHINE_OPERATOR',
  WORKER: 'WORKER',
};

export const WORKER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
};

export const SHIFT_STATUS = {
  PLANNED: 'PLANNED',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
};

export const PRODUCTION_STATUS = {
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  DELAYED: 'DELAYED',
};

export const MACHINE_STATUS = {
  ACTIVE: 'ACTIVE',
  IDLE: 'IDLE',
  MAINTENANCE: 'MAINTENANCE',
  FAULT: 'FAULT',
};

export const MAINTENANCE_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
};

export const INVENTORY_TYPE = {
  RAW_MATERIAL: 'RAW_MATERIAL',
  FINISHED_GOOD: 'FINISHED_GOOD',
};

export const NOTIFICATION_TYPE = {
  LOW_PRODUCTION: 'LOW_PRODUCTION',
  MISSED_TARGET: 'MISSED_TARGET',
  MACHINE_FAILURE: 'MACHINE_FAILURE',
  LOW_INVENTORY: 'LOW_INVENTORY',
  HIGH_REJECTION_RATE: 'HIGH_REJECTION_RATE',
  DOWNTIME: 'DOWNTIME',
};
